### PR TITLE
PROCFILE env arg

### PR DESCRIPTION
**Pull request by BoldBigflank**
This allows you to choose the Procfile from within the .env file using the PROCFILE argument.

### CODE REVIEW

**Comment by nickstenning** [comment]
Looks good. Could you add an integration test and documentation for this change?

**Comment by nickstenning** [comment]
(Oh, and don't worry about the 3.2 build failure. We should probably drop support for 3.2 or pin `coverage` -- either way it's not a problem introduced by this PR.)

**Comment by BoldBigflank** [comment]
All but the python 3.2 build passes. I don't know too much about PRs, do I need to update a minor version number?

**Comment by nickstenning** [comment]
Merged as 5177b51. Thank you!

**Pull request closed without merging**
