### PR TITLE
Be able to pass cwd along to Popen

### PR DESCRIPTION
**Pull request by mattrobenolt**
This is useful when using honcho as a library.

### CODE REVIEW

**Comment by nickstenning** [comment]
Thanks for submitting this. The change looks good, and I'll be happy to merge it if you could add some tests for this functionality.

**Comment by mattrobenolt** [comment]
Yeah, totally. I'll see if I have some time today to get that done. Thanks. :)

**Comment by mattrobenolt** [comment]
jk tests were easy. @nickstenning should be good now. :)

**Comment by mattrobenolt** [comment]
Hey @nickstenning, anything else I can do here?

**Comment by nickstenning** [comment]
Sorry for the delay. LGTM.

**Pull request merged**
