### PR TITLE
Add support for multiline strings in .env

### PR DESCRIPTION
**Pull request by joshfriend**
see ddollar/foreman#250

Very helpful for keys/certs that are stored in environment variables

### CODE REVIEW

**Comment by nickstenning** [comment]
I've gone for a slightly more general approach in 920b0b0, but thank you very much for alerting me to the fact that we broke this in v0.6.5.

**Comment by joshfriend** [comment]
Thanks for fixing this. I had no idea `string_escape` was a thing. TIL

**Comment by nickstenning** [comment]
Unfortunately, the bytestring-to-bytestring decoders were removed Python 3, so I might well have to revert to a regex-based solution. I'll reopen #128 to track this.

**Comment by joshfriend** [comment]
python3 has a `unicode_escape` option, would that work?

**Comment by nickstenning** [comment]
It does, but it complicates things because you can only decode a `bytes` object to a `str` object in Py3, and we get text out of shlex (again, only in Py3), so we'd then have to go text -> binary and back to text again. I'll look into it when I get a moment (won't be today) or if you have time, then I'd be hugely appreciative of anything you manage to submit.

**Comment by joshfriend** [comment]
Yeah if I have time, I will take a look at a potential patch. I've fixed my specific use case in my application code, so no hurry.

**Pull request closed without merging**
